
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_workspace
    username: smart_user
    password: smart_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080